fix: field name in comment
apple/app-store-server-library-python pull request #79
Opened 2024-04-11 19:42 UTC by sunny-dubey

2024-04-12 04:36 UTC, alexanderjordanbaker approved these changes
Thank you

2024-04-12 04:38 UTC, alexanderjordanbaker requested changes
Could you please update this to signedTransaction to match the other libraries? I realized as I went to merge the name we used in other languages was just signedTransaction

2024-04-12 05:47 UTC, sunny-dubey commented
Done!

2024-04-19 06:46 UTC, alexanderjordanbaker approved these changes

2024-04-19 06:47 UTC, merged